services:
  backend:
    build: ./backend_project
    command: daphne -b 0.0.0.0 -p 8000 backend_project.asgi:application
    depends_on:
      - redis
      - db
    volumes:
      - media:/app/media
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: backend_project.settings
      SECRET_KEY: "django-insecure-p=igja**a%y#yy&b#1ttv13k+2gx&%7(g3&&@=nf=x2%(ihgtb"
      DEBUG: "False"
      ALLOWED_HOSTS: "*"
      DATABASE_URL: postgres://ptc_user:ptc@pass.pmgi@db:5432/project_time_central
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    restart: always

  celery:
    build: ./backend_project
    command: celery -A backend_project worker -l info
    depends_on:
      - redis
      - db
    volumes:
      - media:/app/media
    environment:
      DJANGO_SETTINGS_MODULE: backend_project.settings
      SECRET_KEY: "django-insecure-p=igja**a%y#yy&b#1ttv13k+2gx&%7(g3&&@=nf=x2%(ihgtb"
      DEBUG: "False"
      ALLOWED_HOSTS: "*"
      DATABASE_URL: postgres://ptc_user:ptc@pass.pmgi@db:5432/project_time_central
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    restart: always
